name: Notifier
on: [push]
jobs:
  notifyTelegram:
    runs-on: ubuntu-latest
    steps:
    - name: send telegram message
      uses: appleboy/telegram-action@master
      env:
        GITHUB_CONTEXT: ${{ toJSON(github) }}
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        format: markdown
        message: |
          *Пришло обновление ${{ github.event_name }} от пользователя ${{ github.actor }}*
          Репозиторий: ${{ github.repository }}
          Ветка: ${{ github.ref }}
